version: '3.4'

services:
  microservice1.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging:LogLevel:Default=Debug
    ports:
      - "5000:80"
  microservice2.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"